Repository rlarjsdn3/EST-Soft-Team3-3rd-Project, pull requests merged in 2025-08, with the labels that each got.

#20 feat: DashboardViewController에 컬렉션 뷰의 기본 레이아웃 코드 작성, `NetworkService` 파일 이동
  Health/Core/String/Prompt+String.swift
  Health/Core/Utils/Date+Formatter.swift
  Health/Core/Utils/NSObject+Nib.swift
  Health/DesignSystem/Constant/UICollectionView+Constant.swift
  Health/Presentation/Base.lproj/Main.storyboard
  Health/Presentation/Dashboard/Content/DashboardContent.swift
  Health/Presentation/Dashboard/Dashboard.storyboard
  Health/Presentation/Dashboard/DashboardViewController.swift
  Health/Presentation/Dashboard/ViewModel/DashboardViewModel.swift
  Health/Presentation/Dashboard/Views/Cells/DashboardCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DashboardTopBarCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DashboardTopBarCollectionViewCell.xib
  Health/Services/DefaultNetworkService.swift
Labels: enhancement

#30 온보딩화면 - 출생년도부분까지 구현
  Health/Presentation/Onboarding/GenderSelectViewController.swift
  Health/Presentation/Onboarding/HealthInfoViewController.swift
  Health/Presentation/Onboarding/Onboarding.storyboard
  Health/Presentation/Onboarding/OnboardingViewController.swift
  Health/Presentation/Onboarding/SelectAgeViewController.swift
Labels: enhancement

#40 feat: `HealthService` 프로토콜 및 `DefaultHealthService` 코드 구현, 뷰-모델 파일을 `ViewModels` 폴더로 이동
  Health/Application/AppDelegate.swift
  Health/Core/DIContainer/DIContainer+Register.swift
  Health/Core/DIContainer/InjectIdentifier+Keys.swift
  Health/Core/Utils/Extensions/Date+Extension.swift
  Health/Services/DefaultHealthService.swift
  Health/Services/Protocols/HealthService.swift
  Health/ViewModels/AlanViewModel.swift
  Health/ViewModels/DashboardViewModel.swift
Labels: enhancement

#45 feat: healthApp-link UI만 구현 + 키보드 로직 수정
  Health/Presentation/Onboarding/Onboarding.storyboard
  Health/Presentation/Onboarding/OnboardingViews/viewcontrollers/GenderSelectViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/viewcontrollers/HealthLinkViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/viewcontrollers/HeightViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/viewcontrollers/InputAgeViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/viewcontrollers/OnboardingViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/viewcontrollers/WeightViewController.swift
  Health/Resources/Info.plist
Labels: enhancement

#49 feat: 대시보드 화면의 `TobBar` 셀 및 `GoalRingCell` 셀 UI 및 뷰-모델 코드 작성, 레이아웃 수치 일부 조정
  Health/Core/Utils/Date+Formatter.swift
  Health/Core/Views/CircleProgressView/CircleProgressView.swift
  Health/Presentation/Dashboard/Content/DashboardContent.swift
  Health/Presentation/Dashboard/DashboardViewController.swift
  Health/Presentation/Dashboard/Views/Cells/DailyGoalRingCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DailyGoalRingCollectionViewCell.xib
  Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.xib
  Health/Presentation/Dashboard/Views/Cells/DashboardTopBarCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DashboardTopBarCollectionViewCell.xib
  Health/ViewModels/Cells/DailyGoalRingCellViewModel.swift
Labels: enhancement

#53 코어데이터 NSclass, ViewModel 초기모델 구현
  Health/Model/CoreData/Entities/DailyStepEntity+CoreDataClass.swift
  Health/Model/CoreData/Entities/DailyStepEntity+CoreDataProperties.swift
  Health/Model/CoreData/Entities/GoalStepCountEntity+CoreDataClass.swift
  Health/Model/CoreData/Entities/GoalStepCountEntity+CoreDataProperties.swift
  Health/Model/CoreData/Entities/UserInfoEntity+CoreDataClass.swift
  Health/Model/CoreData/Entities/UserInfoEntity+CoreDataProperties.swift
  Health/Model/CoreData/Model.xcdatamodeld/Model.xcdatamodel/contents
  Health/Model/enums/Disease.swift
  Health/Presentation/Onboarding/Onboarding.storyboard
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/GenderSelectViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/HealthLinkViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/HeightViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/InputAgeViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/OnboardingSubVC/ProgressIndicatorStackView.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/OnboardingViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/WeightViewController.swift
  Health/Resources/Info.plist
  Health/ViewModels/EntityViewModels/DailyStepViewModel.swift
  Health/ViewModels/EntityViewModels/GoalStepCountViewModel.swift
  Health/ViewModels/EntityViewModels/UserInfoViewModel.swift
Labels: enhancement

#57 feat: `HealthInfoCard` 셀 UI 및 뷰-모델 코드 작성, 카드 섹션에 알맞은 섹션 헤더 뷰 생성 및 구성
  Health/Presentation/Dashboard/Content/DashboardContent.swift
  Health/Presentation/Dashboard/Content/Enum/DashboardCardStack.swift
  Health/Presentation/Dashboard/Content/Enum/DashboardCardType.swift
  Health/Presentation/Dashboard/Content/Enum/DashboardStackType.swift
  Health/Presentation/Dashboard/DashboardViewController.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.xib
  Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.xib
  Health/Presentation/Dashboard/Views/InfoDetailButton.swift
  Health/ViewModels/Cells/HealthInfoCardCellViewModel.swift
  Health/ViewModels/Cells/HealthInfoStackCellViewModel.swift
Labels: enhancement

#59 feat: info.plist에 Client ID 키 추가, 빌드 스킴에 따라 xcconfig를 받도록 수정, xcconfig에 따라 서로 다른 번들 ID로 세팅되도록 빌드 설정 수정
  .gitignore
  Health.xcodeproj/project.pbxproj
  Health/Application/AppDelegate.swift
  Health/Application/Configuration/AppConfiguration.swift
  Health/Resources/Info.plist
Labels: enhancement

#63 feat: 대시보드 `HealthInfoCard` 셀을 아이패드 화면에 대응, `WarningText` 셀 UI 구현
  Health/Core/Utils/Extensions/NSCollectionLayoutEnvironment+Extension.swift
  Health/Core/Views/CircleProgressView/CircleProgressView.swift
  Health/Presentation/Dashboard/Content/DashboardContent.swift
  Health/Presentation/Dashboard/DashboardViewController.swift
  Health/Presentation/Dashboard/SwiftUI/Views/LineChartsView.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.xib
  Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.xib
  Health/Presentation/Dashboard/Views/Cells/TextCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/TextCollectionViewCell.xib
  Health/ViewModels/Cells/TextCellViewModel.swift
Labels: enhancement

#61 feat/chatbot-response: 챗봇 디버그모드 응답값 처리 - 목데이터 , 에러처리 명세화, 채팅입력창 수정
  Health.xcodeproj/project.pbxproj
  Health/Application/AppDelegate.swift
  Health/Core/Network/NetworkError.swift
  Health/Presentation/Chatbot/Chatbot.storyboard
  Health/Presentation/Chatbot/ChatbotViewController.swift
  Health/Presentation/Chatbot/Views/Cells/AIResponseCell.swift
  Health/Presentation/Chatbot/Views/Cells/AIResponseCell.xib
  Health/Presentation/Chatbot/Views/Cells/BubbleViewCell.swift
  Health/Presentation/Chatbot/Views/Cells/BubbleViewCell.xib
  Health/Presentation/Chatbot/Views/Cells/ChatbotHeaderTitleCell.swift
  Health/Resources/Assets.xcassets/appChatBotBubbleColor.colorset/Contents.json
  Health/Resources/Info.plist
  Health/Services/NetworkService/NetworkMonitor.swift
Labels: enhancement

#68 feat:diseaseView + UI update 구현 (healthKit연동은 아직 미구현)
  Health.xcodeproj/project.pbxproj
  Health/Core/Storage/CoreData/CoreDataStack+Dummy.swift
  Health/Model/enums/Disease.swift
  Health/Presentation/Onboarding/Onboarding.storyboard
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/DiseaseViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/GenderSelectViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/HealthLinkViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/OnboardingCells/DiseaseCollectionViewCell.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/OnboardingViewController.swift
Labels: enhancement

#70 feat: ⚠️ 버튼을 클릭하면 '보행 보폭', '보행 속도' 등 구체적인 의미를 담은 플로팅 시트 또는 얼럿으로 띄우도록 구현
  Health.xcodeproj/project.pbxproj
  Health.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Health/Core/Views/HeaderLabelView/HeaderDescriptionsView.swift
  Health/Core/Views/HeaderLabelView/HeaderStackView.swift
  Health/Presentation/Dashboard/Content/String/WalkingBalanceAnaysis+String.swift
  Health/Presentation/Dashboard/DashboardViewController.swift
  Health/Presentation/Dashboard/Views/InfoDetailButton.swift
Labels: enhancement

#74 feat: HealthKitService에 읽기 권한 여부를 확인하는 메서드 추가 구현
  Health.xcodeproj/project.pbxproj
  Health/Core/Utils/Extensions/Date+Extension.swift
  Health/Presentation/Chatbot/ChatbotViewController.swift
  Health/Services/HealthService/DefaultHealthService.swift
  Health/Services/HealthService/MockHealthService.swift
  Health/Services/HealthService/Protocol/HealthService.swift
  Health/Services/NetworkService/Protocol/NetworkService.swift
Labels: enhancement

#77 헬스킷 연동작업 준비(healthkit framework importing + 일부 ui, color set 수정)
  Health.xcodeproj/project.pbxproj
  Health/Presentation/Onboarding/Onboarding.storyboard
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/DiseaseViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/GenderSelectViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/HealthLinkViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/HeightViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/InputAgeViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/OnboardingCells/DiseaseCollectionViewCell.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/OnboardingViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/WeightViewController.swift
Labels: enhancement

#85 feat: `DailyGoalRing`, `HealthInfoStack` 및 `HealthInfoCard` 셀에 실제 HealthKit 데이터를 주입 및 건강 데이터 불러오기 실패 시, 예외 UI가 뜨도록 구현
  Health/Core/Views/CircleProgressView/CircleProgressView.swift
  Health/Core/Views/StatusProgressBarView/StatusProgressBarView.swift
  Health/Presentation/Dashboard/Content/Enum/DashboardCardType.swift
  Health/Presentation/Dashboard/Content/Enum/DashboardStackType.swift
  Health/Presentation/Dashboard/DashboardViewController.swift
  Health/Presentation/Dashboard/Views/Cells/AlanActivitySummaryCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DailyGoalRingCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.xib
  Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
  Health/ViewModels/Cells/DailyGoalRingCellViewModel.swift
  Health/ViewModels/Cells/HealthInfoCardCellViewModel.swift
  Health/ViewModels/Cells/HealthInfoStackCellViewModel.swift
Labels: enhancement

#81 scene delegate + healthKit Link service + info.plist 작업 구현완료
  Health.xcodeproj/project.pbxproj
  Health/Application/SceneDelegate.swift
  Health/Presentation/Onboarding/Onboarding.storyboard
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/DiseaseViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/HealthLinkViewController.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/OnboardingViewController.swift
  Health/Resources/Info.plist
Labels: enhancement

#97 feat: `DahsboardViewModel`에서 `denied` 상태도 방출, 대시보드의 일부 셀의 UI 색상 및 제약 수정, 라인 차트가 그려지지 않는 문제 수정
  Health/Presentation/Dashboard/Views/Cells/AlanActivitySummaryCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DailyGoalRingCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.xib
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.xib
  Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.xib
  Health/Services/HealthService/MockHealthService.swift
  Health/ViewModels/Cells/HealthInfoStackCellViewModel.swift
  Health/ViewModels/Dashboard/DashboardViewModel.swift
  Health/ViewModels/Dashboard/Enum/LoadState.swift
Labels: enhancement

#103 feat: 대시보드의 각 셀에서 `접근 권한 없음` 뷰를 띄우도록 코드 작성
  Health/Core/Views/PermissionDeniedView/PermissionDeniedCompactView.swift
  Health/Core/Views/PermissionDeniedView/PermissionDeniedFullView.swift
  Health/Presentation/Dashboard/Views/Cells/AlanActivitySummaryCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DailyGoalRingCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DailyGoalRingCollectionViewCell.xib
  Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.xib
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.xib
  Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.xib
  Health/ViewModels/Dashboard/DashboardViewModel.swift
Labels: enhancement

#105 feat: OnboardingNavigationBar + 일부 UI fixed
  Health/Application/SceneDelegate.swift
  Health/Presentation/Onboarding/Onboarding.storyboard
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/OnboardingCells/DiseaseCollectionViewCell.swift
  Health/Presentation/Onboarding/OnboardingViews/OnboardingVC/OnboardingViewController.swift
  Health/Presentation/Onboarding/cells/DiseaseCollectionViewCell.swift
  Health/Presentation/Onboarding/delegates/CustomNavigationBarViewDelegate.swift
  Health/Presentation/Onboarding/mainVC/DiseaseViewController.swift
  Health/Presentation/Onboarding/mainVC/GenderSelectViewController.swift
  Health/Presentation/Onboarding/mainVC/HealthLinkViewController.swift
  Health/Presentation/Onboarding/mainVC/HeightViewController.swift
  Health/Presentation/Onboarding/mainVC/InputAgeViewController.swift
  Health/Presentation/Onboarding/mainVC/OnboardingViewController.swift
  Health/Presentation/Onboarding/mainVC/WeightViewController.swift
  Health/Presentation/Onboarding/subVC/ProgressContainerViewController.swift
  Health/Presentation/Onboarding/subVC/ProgressIndicatorStackView.swift
  Health/Resources/Assets.xcassets/appIconAny.imageset/Contents.json
  Health/Resources/Assets.xcassets/appIconAny.imageset/appIcon-dark@2x.png
  Health/Resources/Assets.xcassets/appIconAny.imageset/appIcon-light@2x.png
Labels: enhancement

#108 feat: `원형 프로그래스 바`의 선 두께 및 색상 변경, `MockHealthService`가 실제 유용한 값을 반환하도록 개선 (수정 #2)
  Health/Core/DIContainer/DIContainer+Register.swift
  Health/Core/DIContainer/InjectIdentifier+Keys.swift
  Health/Core/Indicators/ActivityIndicator/AlanLoadingIndicatorView.swift
  Health/Core/Indicators/ActivityIndicator/CustomActivityIndicatorView.swift
  Health/Core/Storage/CoreData/CoreDataStack+Dummy.swift
  Health/Core/Storage/CoreData/CoreDataStack.swift
  Health/Core/Views/CircleProgressView/CircleProgressView.swift
  Health/Presentation/Dashboard/Views/Cells/AlanActivitySummaryCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
  Health/Resources/Assets.xcassets/appOffWhite.colorset/Contents.json
  Health/Services/CoreDataSerice/DefaultCoreDataUserService.swift
  Health/Services/CoreDataSerice/Protocol/CoreDataUserService.swift
  Health/Services/HealthService/MockHealthService.swift
  Health/Services/HealthService/Protocol/HealthService.swift
  Health/ViewModels/Dashboard/DashboardViewModel.swift
Labels: enhancement

#118 feat: 온보딩 보강작업 (iPad크기대응, keyboardNoti, feedback fix)
  Health/Presentation/Onboarding/Onboarding.storyboard
  Health/Presentation/Onboarding/cells/DiseaseCollectionViewCell.swift
  Health/Presentation/Onboarding/mainVC/DiseaseViewController.swift
  Health/Presentation/Onboarding/mainVC/GenderSelectViewController.swift
  Health/Presentation/Onboarding/mainVC/HealthLinkViewController.swift
  Health/Presentation/Onboarding/mainVC/HeightViewController.swift
  Health/Presentation/Onboarding/mainVC/InputAgeViewController.swift
  Health/Presentation/Onboarding/mainVC/OnboardingViewController.swift
  Health/Presentation/Onboarding/mainVC/WeightViewController.swift
  Health/Presentation/Profile/Views/EditStepGoalView.swift
Labels: enhancement

#129 feat/chatbot : 응답값 잘림 이슈 및 SSE 서비스 코드 추가, DIContainer 등록, 네트워크 연결 모니터 설정(리팩토링)
  Health/Core/DIContainer/DIContainer+Register.swift
  Health/Core/DIContainer/InjectIdentifier+Keys.swift
  Health/Core/Privacy/AddressRegionClassifier.swift
  Health/Core/Utils/Concurrency/NCObserverBox.swift
  Health/Presentation/Chatbot/Chatbot.storyboard
  Health/Presentation/Chatbot/ChatbotViewController.swift
  Health/Presentation/Chatbot/Content/ChatbotContent.swift
  Health/Presentation/Chatbot/Views/Cells/AIResponseCell.swift
  Health/Presentation/Chatbot/Views/Cells/AIResponseCell.xib
  Health/Presentation/Chatbot/Views/Cells/ChatbotHeaderTitleView.swift
  Health/Presentation/Chatbot/Views/Cells/LoadingResponseCell.swift
  Health/Services/NetworkService/SSEService/AlanSSEClient.swift
  Health/Services/NetworkService/SSEService/AlanSSEParser.swift
  Health/Services/NetworkService/SSEService/AlanSSEService.swift
  Health/Services/NetworkService/SSEService/Protocol/AlanSSEClientProtocol.swift
  Health/Services/NetworkService/SSEService/Protocol/AlanSSEServiceProtocol.swift
  Health/ViewModels/AlanViewModel.swift
  Health/ViewModels/ChatbotViewModel.swift
Labels: enhancement

#138 fix: 고장난 GitHub Action 수리, Xcode 버전을 `16.1`에서 `16.4`로 업데이트
  .github/workflows/ci.yml
Labels: enhancement

#137 design: toastable warning - 경고 토스트 메시지 컬러에셋 추가
  Health/Resources/Assets.xcassets/Toastable-warning/Contents.json
  Health/Resources/Assets.xcassets/Toastable-warning/toastStrokeColor.colorset/Contents.json
  Health/Resources/Assets.xcassets/Toastable-warning/toastSubTitleColor.colorset/Contents.json
  Health/Resources/Assets.xcassets/Toastable-warning/toastWarningBgColor.colorset/Contents.json
  Health/Resources/Assets.xcassets/Toastable-warning/warningSymbolColor.colorset/Contents.json
Labels: design

#140 feat: `HealthNavigationBar` 코드 작성, 이미지 리사이징 함수 및 상위 뷰-컨트롤러를 찾아주는 함수 코드 작성 (수정 #1)
  Health/Core/NavigationBar/HealthNavigationBar/HealthNavigationBar.swift
  Health/Core/NavigationBar/HealthNavigationBar/HealthNavigationBarDelegate.swift
  Health/Core/NavigationBar/HealthNavigationBar/HealthNavigationBarItem.swift
  Health/Core/Utils/Extensions/UIImage+Extension.swift
  Health/Core/Utils/Extensions/UIView+Extension.swift
Labels: enhancement

#144 feat: `DashboardTopBarViewModel` 코드작성 및 Pull-to-Referesh 시, 기준 시각이 제대로 갱신되지 않는 문제 수정
  Health/Presentation/Dashboard/Content/DashboardContent.swift
  Health/Presentation/Dashboard/DashboardViewController.swift
  Health/Presentation/Dashboard/Views/Cells/AlanActivitySummaryCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DashboardTopBarCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
  Health/ViewModels/Cells/DashboardBarChartsCellViewModel.swift
  Health/ViewModels/Cells/DashboardTopBarViewModel.swift
  Health/ViewModels/Dashboard/DashboardViewModel.swift
Labels: enhancement

#145 feat: 대시보드에 `HealthNavigationBar` 코드 적용 및 캘린더로부터 대시보드에 진입하면 AI 요약을 하지 않도록 코드 수정
  Health/Core/NavigationBar/HealthNavigationBar/HealthNavigationBar.swift
  Health/Presentation/Dashboard/Dashboard.storyboard
  Health/Presentation/Dashboard/DashboardViewController.swift
  Health/Presentation/Dashboard/Views/AISummaryLabel.swift
  Health/Presentation/Dashboard/Views/Cells/AlanActivitySummaryCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
  Health/ViewModels/Dashboard/DashboardViewModel.swift
Labels: enhancement

#147 feat: 대시보드에서 `일일 AI 활동 요약` 프롬프트 작성
  Health.xcodeproj/project.pbxproj
  Health/Services/PromptBuilderService/DefaultPromptBuilderService.swift
  Health/Services/PromptBuilderService/DefaultPromptRenderService.swift
  Health/Services/PromptBuilderService/PromptContext.swift
  Health/Services/PromptBuilderService/PromptOption.swift
  Health/Services/PromptBuilderService/Protocol/PromptBuilderService.swift
  Health/Services/PromptBuilderService/Protocol/PromptRenderService.swift
  Health/ViewModels/Dashboard/DashboardViewModel.swift
Labels: enhancement

#159 feat: 몸무게뷰,신장뷰 로직 수정
  Health/Presentation/Onboarding/MainVC/HeightViewController.swift
  Health/Presentation/Onboarding/MainVC/WeightViewController.swift
Labels: bug, enhancement

#165 feat: 버튼 하이라이트추가 + 헬스킷 로직 변경 (PR설명 참고)
  Health/Presentation/Onboarding/MainVC/DiseaseViewController.swift
  Health/Presentation/Onboarding/MainVC/GenderSelectViewController.swift
  Health/Presentation/Onboarding/MainVC/HealthLinkViewController.swift
  Health/Presentation/Onboarding/MainVC/HeightViewController.swift
  Health/Presentation/Onboarding/MainVC/InputAgeViewController.swift
  Health/Presentation/Onboarding/MainVC/OnboardingViewController.swift
  Health/Presentation/Onboarding/MainVC/StepGoalViewController.swift
  Health/Presentation/Onboarding/MainVC/WeightViewController.swift
Labels: enhancement

#166 feat: TSAlertController 패키지 업데이트, `Alertable` 코드 최적화
  Health.xcodeproj/project.pbxproj
  Health.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Health/Core/Protocols/Alertable.swift
Labels: enhancement

#194 Feat/qa onboarding 2nd fix
  Health/Presentation/Onboarding/MainVC/HeightViewController.swift
  Health/Presentation/Onboarding/MainVC/InputAgeViewController.swift
  Health/Presentation/Onboarding/MainVC/WeightViewController.swift
  Health/Presentation/Onboarding/Onboarding.storyboard
  Health/Presentation/Onboarding/SubVC/DynamicWidthTextField.swift
Labels: enhancement

#199 Feat/chatbot bug fix: 챗봇 맞춤 토스터블 메시지 위치 수정, 위젯 관련 빌드 세팅 수정, 챗봇 채팅창 UI 수정
  Health.xcodeproj/project.pbxproj
  Health/Core/Protocols/ToastType.swift
  Health/Core/Protocols/Toastable.swift
  Health/Core/Shared/SharedStore.swift
  Health/Presentation/Chatbot/Chatbot.storyboard
  Health/Presentation/Chatbot/ChatbotViewController.swift
  Health/Presentation/Chatbot/Views/Cells/ChatbotHeaderTitleView.swift
  HealthWidget/Info.plist
Labels: design

#203 feat: 온보딩 QA UI 버그 및 불일치한 부분 픽스 (최종)
  Health/Presentation/Onboarding/Cells/DiseaseCollectionViewCell.swift
  Health/Presentation/Onboarding/Delegates/CustomOnboardingNaviBarView.swift
  Health/Presentation/Onboarding/MainVC/DiseaseViewController.swift
  Health/Presentation/Onboarding/MainVC/GenderSelectViewController.swift
  Health/Presentation/Onboarding/MainVC/HealthLinkViewController.swift
  Health/Presentation/Onboarding/MainVC/HeightViewController.swift
  Health/Presentation/Onboarding/MainVC/InputAgeViewController.swift
  Health/Presentation/Onboarding/MainVC/OnboardingViewController.swift
  Health/Presentation/Onboarding/MainVC/StepGoalViewController.swift
  Health/Presentation/Onboarding/MainVC/WeightViewController.swift
  Health/Presentation/Onboarding/Onboarding.storyboard
  Health/Resources/Assets.xcassets/OnboardingIcons/Contents.json
  Health/Resources/Assets.xcassets/OnboardingIcons/HealthAppIcon.imageset/Contents.json
  Health/Resources/Assets.xcassets/OnboardingIcons/HealthAppIcon.imageset/HealthAppIcon@2x.png
  Health/Resources/Assets.xcassets/OnboardingIcons/calandarIcon.imageset/Contents.json
  Health/Resources/Assets.xcassets/OnboardingIcons/calandarIcon.imageset/calandarIcon@2x.png
  Health/Resources/Assets.xcassets/OnboardingIcons/chatbotIcon.imageset/Contents.json
  Health/Resources/Assets.xcassets/OnboardingIcons/chatbotIcon.imageset/chatbotIcon@2x.png
  Health/Resources/Assets.xcassets/OnboardingIcons/dashboardIcon.imageset/Contents.json
  Health/Resources/Assets.xcassets/OnboardingIcons/dashboardIcon.imageset/dashIcon@2x.png
  Health/Resources/Assets.xcassets/Toastable-warning/chatbotIcon.imageset/chatbotIcon@2x.png
Labels: enhancement

#211 feat: 앱 최초 실행 시, 목표 걸음 수가 제대로 출력되지 않는 문제 수정
  Health/Services/StepSync/StepSyncService.swift
  Health/ViewModels/Dashboard/DashboardViewModel.swift
Labels: enhancement

#210 feat: 권한 로직 원상복구
  Health/Presentation/Onboarding/MainVC/HealthLinkViewController.swift
Labels: enhancement

#219 fix: 프로필에서 건강 스위치를 `on`하더라도 대시보드가 실시간으로 갱신되지 않는 문제 수정
  Health/Presentation/Dashboard/DashboardViewController.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
  Health/Presentation/Profile/ProfileViewController.swift
Labels: enhancement

#221 feat: extension - array, date, double 단위테스트코드 작성완료
  Health/Core/Utils/Extensions/Array+Extension.swift
  HealthTests/Core/Extensions/ArrayExtensionTests.swift
  HealthTests/Core/Extensions/DateExtensionsTests.swift
  HealthTests/Core/Extensions/DoubleExtensionTests.swift
Labels: QA

#214 Feat/qa chatbot: 챗봇 QA 테스트 및 UIUX 개선 사항 수정
  Health.xcodeproj/xcshareddata/xcbaselines/C76490C22E3790410062054D.xcbaseline/4CAD5EE4-1892-4C66-A905-03FC9F3ADE60.plist
  Health.xcodeproj/xcshareddata/xcbaselines/C76490C22E3790410062054D.xcbaseline/Info.plist
  Health/Core/CoreGradientViewController.swift
  Health/Core/Utils/Notification+Name.swift
  Health/Presentation/Chatbot/Chatbot.storyboard
  Health/Presentation/Chatbot/ChatbotViewController.swift
  Health/Presentation/Chatbot/Views/Cells/ChatbotHeaderTitleView.swift
  Health/Services/NetworkService/SSEService/AlanSSEParser.swift
  Health/ViewModels/ChatbotViewModel.swift
  HealthTests/ViewModels/Chatbot/ChatbotViewModelTests.swift
  HealthTests/ViewModels/Chatbot/Support/AlanStreamingResponse+Factory.swift
  HealthTests/ViewModels/Chatbot/Support/MockPromptBuilderService.swift
  HealthTests/ViewModels/Chatbot/Support/MockSSEService.swift
  HealthTests/ViewModels/Chatbot/Support/ResetCountingNetworkService.swift
  HealthTests/ViewModels/Chatbot/TestHealthService.swift
Labels: QA

#227 feat: 경고창 message 문구 통일 작업 + 네비게이션바 백버튼 상하좌우 터치 대응 되도록 여백 수정
  Health/Presentation/Onboarding/Delegates/CustomOnboardingNaviBarView.swift
  Health/Presentation/Onboarding/MainVC/HealthLinkViewController.swift
  Health/Presentation/Onboarding/Onboarding.storyboard
Labels: enhancement, QA

#226 feat: 에셋 파일에서 색상 수정, 대시보드에서 권한 요청 알림 문구 수정, 대시보드 셀에서 그림자 불투명도 수정, 프로젝트 DisplayName 설정
  Health.xcodeproj/project.pbxproj
  Health/Presentation/Dashboard/DashboardViewController.swift
  Health/Presentation/Dashboard/Views/Cells/AlanActivitySummaryCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/DashboardBarChartsCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
  Health/Resources/Assets.xcassets/boxBgColor.colorset/Contents.json
Labels: enhancement

#231 feat: 헬스킷에서 `오른 층수` 권한을 받도록 수정, 대시보드에서 운동 시간 대신 `오른 층수`가 표시되도록 수정
  Health/Core/Protocols/ScrollableToTop.swift
  Health/Core/Views/CircleProgressView/CircleProgressView.swift
  Health/Presentation/Dashboard/Content/Enum/DashboardStackKind.swift
  Health/Presentation/Dashboard/DashboardViewController.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoStackCollectionViewCell.swift
  Health/Presentation/Profile/ProfileViewController.swift
  Health/Services/HealthService/DefaultHealthService.swift
  Health/Services/HealthService/MockHealthService.swift
  Health/ViewModels/Dashboard/DashboardViewModel.swift
Labels: enhancement

#236 feat: 성별버튼 비활성화 상태 색상 변환 (boxBG -> systemGray5)
  Health/Presentation/Onboarding/MainVC/GenderSelectViewController.swift
  Health/ViewModels/EntityViewModels/UserInfoViewModel.swift
Labels: enhancement, QA

#234 feat: 날짜가 바뀌면 정확한 목표 걸음 수를 제대로 가져오지 못하는 문제 수정
  Health/Core/Utils/Extensions/Date+Extension.swift
  Health/Presentation/Calendar/CalendarViewController.swift
  Health/Presentation/Dashboard/Content/Enum/DashboardCardKind.swift
  Health/Presentation/Dashboard/DashboardViewController.swift
  Health/Presentation/Dashboard/Views/Cells/HealthInfoCardCollectionViewCell.swift
  Health/Services/PromptBuilderService/DefaultPromptBuilderService.swift
  Health/Services/StepSync/StepSyncService.swift
  Health/ViewModels/AlanViewModel.swift
  Health/ViewModels/Dashboard/DashboardViewModel.swift
  Health/ViewModels/EntityViewModels/DailyStepViewModel.swift
Labels: enhancement

#237 feat/qa-chatbot 3: 상세주소 비식별화 처리(오탐 5,60%), 401 코드 사용자 매핑, 스크롤 처리
  Health/Core/Privacy/AddressRegionClassifier.swift
  Health/Presentation/Chatbot/Chatbot.storyboard
  Health/Presentation/Chatbot/ChatbotViewController.swift
  Health/Presentation/Chatbot/Content/ChatbotWaitingState.swift
  Health/Services/PrivacyService/PrivacyService.swift
  Health/Services/PromptBuilderService/PromptOption.swift
  Health/ViewModels/ChatbotViewModel.swift
  HealthTests/ViewModels/Chatbot/ChatbotViewModelTests.swift
Labels: QA

#241 feat: QA extension XCTest fix + weight fix
  Health/Presentation/Onboarding/MainVC/HealthLinkViewController.swift
  Health/Presentation/Onboarding/MainVC/InputAgeViewController.swift
  Health/Presentation/Onboarding/MainVC/WeightViewController.swift
  Health/Presentation/Onboarding/Onboarding.storyboard
  HealthTests/Core/Extensions/DateExtensionsTests.swift
Labels: QA

#243 feat: 대시보드 AI 요약에서 마크다운 문법이 제거가 안되는 문제 수정
  Health/Presentation/Dashboard/DashboardViewController.swift
  Health/ViewModels/Dashboard/DashboardViewModel.swift
  HealthTests/Core/Extensions/DateExtensionsTests.swift
Labels: enhancement

#252 feat: 대시보드 일일 AI 요약 프롬프트 수정
  Health/Services/PromptBuilderService/PromptOption.swift
Labels: enhancement

#258 Docs/chatbot: 챗봇을 구성하는 Utils, UIComponents, Views/Cell, 뷰모델 등의 DocC 문서화 작업 및 위젯 익스텐션 디바이스 타겟 수정
  Health.xcodeproj/project.pbxproj
  Health/Core/CoreGradientViewController.swift
  Health/Core/Privacy/AddressRegionClassifier.swift
  Health/Core/Privacy/DistrictModels.swift
  Health/Presentations/Chatbot/Adapters/ChatbotStreamingBinder.swift
  Health/Presentations/Chatbot/Adapters/ChatbotTableAdapter.swift
  Health/Presentations/Chatbot/ChatbotViewController.swift
  Health/Presentations/Chatbot/Content/ChatbotMessageContent.swift
  Health/Presentations/Chatbot/Content/ChatbotWaitingState.swift
  Health/Presentations/Chatbot/UIComponents/ChatAutoScrollManager.swift
  Health/Presentations/Chatbot/UIComponents/ChatInputBarController.swift
  Health/Presentations/Chatbot/UIComponents/Keyboard/KeyboardEvents.swift
  Health/Presentations/Chatbot/UIComponents/Keyboard/KeyboardObserver.swift
  Health/Presentations/Chatbot/Utils/Concurrency/NCObserverBox.swift
  Health/Presentations/Chatbot/Utils/Extensions/UITextField+Padding.swift
  Health/Presentations/Chatbot/Views/Cells/AIResponseCell.swift
  Health/Presentations/Chatbot/Views/Cells/BubbleViewCell.swift
  Health/Presentations/Chatbot/Views/Cells/LoadingResponseCell.swift
  Health/Services/WidgetSync/DefaultDashboardSnapshotProvider.swift
  Health/ViewModels/Chatbot/ChatbotViewModel.swift
  HealthTests/ViewModels/Chatbot/ChatbotViewModelTests.swift
  HealthTests/ViewModels/Chatbot/Support/MockPromptBuilderService.swift
  HealthTests/ViewModels/Chatbot/Support/MockSSEService.swift
  HealthWidget/Design/AdaptiveMetrics.swift
  HealthWidget/HealthWidget.swift
  HealthWidget/Views/HealthDashboardMediumView.swift
Labels: documentation
